# Generated by Django 3.1.1 on 2020-09-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20200908_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='diet_plan',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='workout_plan',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.goal'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.goal'),
        ),
    ]
