# Generated by Django 3.1.1 on 2020-09-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Seafood', 'Seafood'), ('Meat', 'Meat'), ('Other', 'Other')], max_length=12, null=True)),
                ('description', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='')),
                ('ingredients', models.TextField()),
                ('prep_time', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Exercise', 'Exercise'), ('Meal-Prep', 'Meal-Prep'), ('Recipe', 'Recipe'), ('Other', 'Other')], max_length=12)),
            ],
        ),
    ]
