# Generated by Django 3.1.1 on 2020-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_video_video_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeImage',
            new_name='Recipe',
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='youtube-default.jpg', null=True, upload_to='video_thumbnail'),
        ),
    ]
