# Generated by Django 3.1.1 on 2020-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200905_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='recipe-default.jpg', null=True, upload_to='recipe_pics'),
        ),
    ]
