# Generated by Django 3.1.1 on 2020-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200904_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='category',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Snack', 'Snack'), ('Side', 'Side'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
