# Generated by Django 3.1 on 2020-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=25)),
                ('plan_type', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group'), ('Couple', 'Couple'), ('Family', 'Family'), ('Corporate', 'Corporate')], max_length=12)),
                ('duration', models.DurationField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
