# Generated by Django 3.1 on 2020-09-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200902_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='duration (months)',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-month', '1-Month'), ('3-months', '3-Months'), ('6-months', '6-Months'), ('1-year', '1-Year')], max_length=10, null=True),
        ),
    ]
