# Generated by Django 3.1.1 on 2020-09-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Leg', 'Leg'), ('Arm', 'Arm'), ('Abs', 'Abs'), ('Full-body', 'Full-Body'), ('Other', 'Other')], max_length=10)),
                ('equipments', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Other', 'Other')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Seafood', 'Seafood'), ('Meat', 'Meat'), ('Other', 'Other')], max_length=12, null=True)),
                ('category', models.CharField(blank=True, choices=[('Main', 'Main'), ('Snack', 'Snack'), ('Side', 'Side'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Other', 'Other')], max_length=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
