# Generated by Django 3.1.1 on 2020-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20200908_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='mins',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='reps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='rounds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
