# Generated by Django 3.1 on 2020-08-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_startTime',
            field=models.TimeField(),
        ),
    ]
