# Generated by Django 3.1.1 on 2020-09-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200904_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='customers',
            new_name='members',
        ),
    ]
