# Generated by Django 3.1.1 on 2020-09-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_auto_20200905_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('weight-loss', 'Weight-Loss'), ('weight-gain', 'Weight-Gain'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=12, null=True)),
                ('target_date', models.DateField()),
                ('start_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goal_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_BMI', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goal_BMI', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('daily_calorie_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('protein', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs', models.PositiveIntegerField(blank=True, null=True)),
                ('fat', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
