# Generated by Django 3.1.1 on 2020-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20200908_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
