# Generated by Django 3.1 on 2020-09-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200902_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(choices=[('1-month', '1-Month'), ('3-months', '3-Months'), ('6-months', '6-Months'), ('1-year', '1-Year')], max_length=10),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='discount percentage')),
                ('final_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('members', models.ManyToManyField(to='members.Customer')),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.membershipplan')),
            ],
        ),
    ]
