# Generated by Django 3.1.1 on 2020-09-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200904_0233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='members',
        ),
        migrations.AddField(
            model_name='membership',
            name='customers',
            field=models.ManyToManyField(to='members.Member'),
        ),
    ]
