# Generated by Django 3.1.1 on 2020-09-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20200910_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
    ]
